#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := udp

ESPBAUD = 921600	# 460800

include $(IDF_PATH)/make/project.mk

