#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := udp

EXTRA_COMPONENT_DIRS := ../esp-idf-lib/components

ESPBAUD = 921600

include $(IDF_PATH)/make/project.mk

